version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

  web:
    build: .
    restart: always
    ports:
      - 8080:8080
      - 8443:443
    depends_on:
      - db
    environment:
      MOODLE_DOCKER_DB_HOST: db
      MOODLE_DOCKER_DB_USER: moodleuser
      MOODLE_DOCKER_DB_PASSWORD: secret
      MOODLE_DOCKER_DB_NAME: moodle
      MOODLE_DOCKER_WWWROOT: http://localhost
      MOODLE_DOCKER_MOODLEDATA: /var/www/moodledata
      MOODLE_DOCKER_SKIP_INSTALL: "false"
      MOODLE_DOCKER_PHP: php
    image: balabox-identification:latest

volumes:
  db_data:
