FROM php:7.4-apache

RUN apt-get update && apt-get install -y \
    unzip \
    libfreetype6-dev \
    libjpeg-dev \
    libpng-dev \
    libicu-dev \
    libxml2-dev \
    libzip-dev

RUN docker-php-ext-configure gd --with-freetype --with-jpeg

RUN docker-php-ext-install \
    gd \
    intl \
    mysqli \
    pdo_mysql \
    soap \
    xmlrpc \
    zip

COPY moodle /var/www/html/

RUN chown -R www-data:www-data /var/www/html/

EXPOSE 80
