version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      MOODLE_DB_TYPE: pgsql # Modification ici
      MOODLE_DB_HOST: db
      MOODLE_DB_NAME: moodle
      MOODLE_DB_USER: moodle
      MOODLE_DB_PASS: moodle
      MOODLE_URL: http://localhost # Modification ici
      SITE_URL: http://localhost # Modification ici
    volumes:
      - ./moodle:/var/www/html
    networks:
      - moodlenet

  db:
    image: postgres:13-alpine # Modification ici
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data # Modification ici
    environment:
      POSTGRES_PASSWORD: moodle # Modification ici
      POSTGRES_DB: moodle # Modification ici
      POSTGRES_USER: moodle # Modification ici
    networks:
      - moodlenet

networks:
  moodlenet:
